<?php
echo $this->doctype();
$user = $this->identity();
?>

<html lang="en">
    <head>
        <meta http-equiv="Content-type" content="text/html; charset=utf-8">
        <meta content="" name="description"/>
        <meta content="" name="author"/>

        <?php echo $this->headTitle('ZF2 ' . $this->translate('Skeleton Application'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php
        echo $this->headMeta()
                ->appendName('viewport', 'width=device-width, initial-scale=1.0')
                ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <link href="http://fonts.googleapis.com/css?family=Open+Sans:400,300,600,700&subset=all" rel="stylesheet" type="text/css"/>
        <link href="<?php echo $this->basePath(); ?>/assets/global/plugins/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css"/>
        <link href="<?php echo $this->basePath(); ?>/assets/global/plugins/simple-line-icons/simple-line-icons.min.css" rel="stylesheet" type="text/css"/>
        <link href="<?php echo $this->basePath(); ?>/assets/global/plugins/bootstrap/css/bootstrap.min.css" rel="stylesheet" type="text/css"/>
        <link href="<?php echo $this->basePath(); ?>/assets/global/plugins/uniform/css/uniform.default.css" rel="stylesheet" type="text/css"/>
        <link href="<?php echo $this->basePath(); ?>/assets/global/plugins/bootstrap-switch/css/bootstrap-switch.min.css" rel="stylesheet" type="text/css"/>
        <!-- END GLOBAL MANDATORY STYLES -->
        <!-- BEGIN THEME STYLES -->
        <link href="<?php echo $this->basePath(); ?>/assets/global/css/components.css" id="style_components" rel="stylesheet" type="text/css"/>
        <link href="<?php echo $this->basePath(); ?>/assets/global/css/plugins.css" rel="stylesheet" type="text/css"/>
        <link href="<?php echo $this->basePath(); ?>/assets/admin/layout/css/layout.css" rel="stylesheet" type="text/css"/>
        <link id="style_color" href="<?php echo $this->basePath(); ?>/assets/admin/layout/css/themes/darkblue.css" rel="stylesheet" type="text/css"/>
        <link href="<?php echo $this->basePath(); ?>/assets/admin/layout/css/custom.css" rel="stylesheet" type="text/css"/>
        <!-- BEGIN THEME STYLES -->

        <!-- Le styles -->
        <?php
        /*echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                ->appendStylesheet($this->basePath() . '/assets/global/plugins/font-awesome/css/font-awesome.min.css')
                ->appendStylesheet($this->basePath() . '/assets/global/plugins/simple-line-icons/simple-line-icons.min.css')
                ->appendStylesheet($this->basePath() . '/assets/global/plugins/bootstrap/css/bootstrap.min.css')
                ->appendStylesheet($this->basePath() . '/assets/global/plugins/uniform/css/uniform.default.css')
                ->appendStylesheet($this->basePath() . '/assets/global/plugins/bootstrap-switch/css/bootstrap-switch.min.css')
                ->appendStylesheet($this->basePath() . '/assets/global/plugins/select2/select2.css')
                ->appendStylesheet($this->basePath() . '/assets/global/plugins/ion.rangeslider/css/ion.rangeSlider.css')
                ->appendStylesheet($this->basePath() . '/assets/global/plugins/ion.rangeslider/css/ion.rangeSlider.Metronic.css')
                ->appendStylesheet($this->basePath() . '/assets/global/css/components.css')
                ->appendStylesheet($this->basePath() . '/assets/global/css/plugins.css')
                ->appendStylesheet($this->basePath() . '/assets/admin/layout/css/layout.css')
                ->appendStylesheet($this->basePath() . '/assets/admin/layout/css/themes/darkblue.css')
                ->appendStylesheet($this->basePath() . '/assets/admin/layout/css/custom.css')*/
        ?>
    </head>
    <body class="page-header-fixed page-quick-sidebar-over-content page-sidebar-closed">
        <!-- BEGIN HEADER -->
        <div class="page-header navbar navbar-fixed-top">
            <div class="page-logo">
                <a style="margin-top: 16px;" href="<?php echo $this->basePath() ?>">
                    <!--<img src="<?php echo $this->basePath(); ?>/assets/admin/layout/img/logo.png"  height="24px" alt="logo" class="logo-default"/>--><span>CERTIFICATION</span>
                </a>
            </div>

            <!-- BEGIN RESPONSIVE MENU TOGGLER -->
            <a href="javascript:;" class="menu-toggler responsive-toggler" data-toggle="collapse" data-target=".navbar-collapse">
            </a>
            <!-- END RESPONSIVE MENU TOGGLER -->
            <!-- BEGIN TOP NAVIGATION MENU -->
<?php if ($user = $this->identity()) { ?>
                <div class="top-menu">
                    <ul class="nav navbar-nav pull-right">
                        <!-- END TODO DROPDOWN -->
                        <!-- BEGIN USER LOGIN DROPDOWN -->
                        <!-- DOC: Apply "dropdown-dark" class after below "dropdown-extended" to change the dropdown styte -->
                        <li class="dropdown dropdown-user">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-close-others="true">
                                <span class="username username-hide-on-mobile">
    <?php echo $this->escapeHtml($user->getFirstname()); ?>&nbsp;<?php echo $this->escapeHtml($user->getLastname()); ?> </span>
                                <i class="fa fa-angle-down"></i>
                            </a>
                            <ul class="dropdown-menu dropdown-menu-default">
                                <li>
                                    <a href="<?php echo $this->url('user-register', array('action' => 'edit-profile'));?>">
                                        <i class="icon-user"></i> My Profile </a>
                                </li>
                                <li class="divider">
                                </li>
                                <li>
                                    <a href="<?php echo $this->url('user-index', array('action' => 'logout')); ?>">
                                        <i class="icon-key"></i> Log Out </a>
                                </li>
                            </ul>
                        </li>
                        <!-- END USER LOGIN DROPDOWN -->
                        <!-- BEGIN QUICK SIDEBAR TOGGLER -->
                        <!-- DOC: Apply "dropdown-dark" class after below "dropdown-extended" to change the dropdown styte -->
                        <li class="dropdown dropdown-quick-sidebar-toggler">
                            <a href="javascript:;" class="dropdown-toggle">
                                <i class="icon-logout"></i>
                            </a>
                        </li>
                        <!-- END QUICK SIDEBAR TOGGLER -->
                    </ul>
                </div>
                <!-- END TOP NAVIGATION MENU -->
<?php } ?>

        </div>
        <!-- END HEADER -->
        <div class="clearfix">
        </div>
        <!-- BEGIN CONTAINER -->
        <div class="page-container">
            
	<!-- BEGIN SIDEBAR -->
	
	<div class="page-sidebar-wrapper">
		<!-- DOC: Set data-auto-scroll="false" to disable the sidebar from auto scrolling/focusing -->
		<!-- DOC: Change data-auto-speed="200" to adjust the sub menu slide up/down speed -->
		<div class="page-sidebar navbar-collapse collapse">
			<!-- BEGIN SIDEBAR MENU -->
			<!-- DOC: Apply "page-sidebar-menu-light" class right after "page-sidebar-menu" to enable light sidebar menu style(without borders) -->
			<!-- DOC: Apply "page-sidebar-menu-hover-submenu" class right after "page-sidebar-menu" to enable hoverable(hover vs accordion) sub menu mode -->
			<!-- DOC: Apply "page-sidebar-menu-closed" class right after "page-sidebar-menu" to collapse("page-sidebar-closed" class must be applied to the body element) the sidebar sub menu mode -->
			<!-- DOC: Set data-auto-scroll="false" to disable the sidebar from auto scrolling/focusing -->
			<!-- DOC: Set data-keep-expand="true" to keep the submenues expanded -->
			<!-- DOC: Set data-auto-speed="200" to adjust the sub menu slide up/down speed -->
			<ul class="page-sidebar-menu page-sidebar-menu-closed" data-keep-expanded="false" data-auto-scroll="true" data-slide-speed="200">
				<!-- DOC: To remove the sidebar toggler from the sidebar you just need to completely remove the below "sidebar-toggler-wrapper" LI element -->
				<li class="sidebar-toggler-wrapper">
					<!-- BEGIN SIDEBAR TOGGLER BUTTON -->
					<div class="sidebar-toggler">
					</div>
					<!-- END SIDEBAR TOGGLER BUTTON -->
				</li>
				<!-- DOC: To remove the search box from the sidebar you just need to completely remove the below "sidebar-search-wrapper" LI element -->
				<li class="sidebar-search-wrapper">
					<!-- BEGIN RESPONSIVE QUICK SEARCH FORM -->
					<!-- DOC: Apply "sidebar-search-bordered" class the below search form to have bordered search box -->
					<!-- DOC: Apply "sidebar-search-bordered sidebar-search-solid" class the below search form to have bordered & solid search box -->
					<form class="sidebar-search " action="extra_search.html" method="POST">
						<a href="javascript:;" class="remove">
						<i class="icon-close"></i>
						</a>
						<div class="input-group">
							<input type="text" class="form-control" placeholder="Search...">
							<span class="input-group-btn">
							<a href="javascript:;" class="btn submit"><i class="icon-magnifier"></i></a>
							</span>
						</div>
					</form>
					<!-- END RESPONSIVE QUICK SEARCH FORM -->
				</li>
				<li  class="star active open">
					<a href="javascript:;">
					<i class="icon-docs"></i>
					<span class="title">Menu</span>
					<span class="arrow "></span>
					</a>
					<ul class="sub-menu">
                                            <?php if ($user = $this->identity()) { ?>
						<li>
							<a href="<?php echo $this->url('user-admin'); ?>">
							Users</a>
						</li>					
                                            <?php } else{ ?>
                                                <li>
							<a href="<?php echo $this->url('user-index',array('action'=>'login')); ?>">
							Login</a>
						</li>
                                            <?php } ?>    
					</ul>
				</li>
			</ul>
			<!-- END SIDEBAR MENU -->
		</div>
	</div>
	
	<!-- END SIDEBAR -->
            <!-- BEGIN CONTENT -->
            <div class="page-content-wrapper">
                <div class="page-content">
<?php echo $this->content; ?>
                </div>
            </div>
            <!-- END QUICK SIDEBAR -->
        </div>
        <!-- END CONTAINER -->
        <!-- BEGIN FOOTER -->
        <div class="page-footer">
            <div class="page-footer-inner">
                2015 &copy; Early Design.
            </div>
            <div class="scroll-to-top">
                <i class="icon-arrow-up"></i>
            </div>
        </div>
        <!-- END FOOTER -->
        <!-- BEGIN JAVASCRIPTS(Load javascripts at bottom, this will reduce page load time) -->
        <!-- BEGIN CORE PLUGINS -->
        <!--[if lt IE 9]>
        <script src="<?php echo $this->basePath(); ?>/assets/global/plugins/respond.min.js"></script>
        <script src="<?php echo $this->basePath(); ?>/assets/global/plugins/excanvas.min.js"></script> 
        <![endif]-->
        <script src="<?php echo $this->basePath(); ?>/assets/global/plugins/jquery.min.js" type="text/javascript"></script>
        <script src="<?php echo $this->basePath(); ?>/assets/global/plugins/jquery-migrate.min.js" type="text/javascript"></script>
        <!-- IMPORTANT! Load jquery-ui-1.10.3.custom.min.js before bootstrap.min.js to fix bootstrap tooltip conflict with jquery ui tooltip -->
        <script src="<?php echo $this->basePath(); ?>/assets/global/plugins/jquery-ui/jquery-ui-1.10.3.custom.min.js" type="text/javascript"></script>
        <script src="<?php echo $this->basePath(); ?>/assets/global/plugins/bootstrap/js/bootstrap.min.js" type="text/javascript"></script>
        <script src="<?php echo $this->basePath(); ?>/assets/global/plugins/bootstrap-hover-dropdown/bootstrap-hover-dropdown.min.js" type="text/javascript"></script>
        <script src="<?php echo $this->basePath(); ?>/assets/global/plugins/jquery-slimscroll/jquery.slimscroll.min.js" type="text/javascript"></script>
        <script src="<?php echo $this->basePath(); ?>/assets/global/plugins/jquery.blockui.min.js" type="text/javascript"></script>
        <script src="<?php echo $this->basePath(); ?>/assets/global/plugins/jquery.cokie.min.js" type="text/javascript"></script>
        <script src="<?php echo $this->basePath(); ?>/assets/global/plugins/uniform/jquery.uniform.min.js" type="text/javascript"></script>
        <script src="<?php echo $this->basePath(); ?>/assets/global/plugins/bootstrap-switch/js/bootstrap-switch.min.js" type="text/javascript"></script>
        <!-- END CORE PLUGINS -->
       <?php echo (isset($this->js_script)) ? $this->js_script[0] : ''; ?>
        <!-- BEGIN PAGE LEVEL SCRIPTS -->
        <script src="<?php echo $this->basePath(); ?>/assets/global/scripts/metronic.js" type="text/javascript"></script>
        <script src="<?php echo $this->basePath(); ?>/assets/admin/layout/scripts/layout.js" type="text/javascript"></script>
        <script src="<?php echo $this->basePath(); ?>/assets/admin/layout/scripts/quick-sidebar.js" type="text/javascript"></script>
        <script src="<?php echo $this->basePath(); ?>/assets/admin/layout/scripts/demo.js" type="text/javascript"></script>
        <!--<script src="<?php echo $this->basePath(); ?>/assets/admin/pages/scripts/components-ion-sliders.js"></script>-->
        <!-- END PAGE LEVEL SCRIPTS -->
        <script>
            jQuery(document).ready(function () {
                // initiate layout and plugins
                Metronic.init(); // init metronic core components
                Layout.init(); // init current layout
                QuickSidebar.init(); // init quick sidebar
                Demo.init(); // init demo features  // set current page
                //ComponentsIonSliders.init();
                <?php echo (isset($this->js_script)) ? $this->js_script[1] : ''; ?>
            });
        </script>         
        <!-- END JAVASCRIPTS -->
    </body>
    <!-- END BODY -->
</html>